### ISSUE TITLE
1.0.4 Throws 'Eager Load' Error on Rails 3.2

### ISSUE THREAD

**Issue by jamescgibson** [parndt/decorators#11]
I am working on a legacy Rails 3.2 application that requires decorators through forem. Decorators 1.0.4, in our setup, throws the following error when attempting to start the application on Heroku or with `bundle exec thin start -R config.ru -e production`:

```
/home/james/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/railties-3.2.17/lib/rails/railtie/configuration.rb:85:in `method_missing': undefined method `eager_load' for #<Rails::Application::Configuration:0x0000000555cb48> (NoMethodError)
        from /home/james/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/decorators-1.0.4/lib/decorators/railtie.rb:9:in `block in <class:Railtie>'
```

We're using Rails 3.2.17 and Railties 3.2.17. Not sure if this is intended behavior or not, but 1.0.3 works in our application, so this problem would go through pessimistic semver. 

Thanks!

**Comment by javinto** [comment]
I can confirm having this issue myself as well after running bundle update on a RefineryCMS 2.1.5 installation. Putting gem 'decorators', '1.03' in my gemfile solved it.

**Comment by parndt** [comment]
Confirm, I lacked CI on this. I'm going to yank 1.0.4 and release it as 2.0.0

Apologies!

**Comment by parndt** [comment]
Pushed 2.0.0 and yanked 1.0.4 - thanks!

**Comment by Nickk4** [comment]
Sorry about this, but when I run ```rails _3.2.12_ new rickrockstar -m http://refinerycms.com/t/2.1.0``` I stil get the error message:
```
        rake    db:create
    generate    refinery:cms --fresh-installation rickrockstar -m http://refiner
ycms.com/t/2.1.0
DL is deprecated, please use Fiddle
D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3.2.12/lib/rai
ls/railtie/configuration.rb:85:in `method_missing': undefined method `eager_load
' for #<Rails::Application::Configuration:0x4631388> (NoMethodError)
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/decorators
-1.0.4/lib/decorators/railtie.rb:9:in `block in <class:Railtie>'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/lazy_load_hooks.rb:34:in `call'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'

        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/lazy_load_hooks.rb:42:in `each'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/application/bootstrap.rb:69:in `block in <module:Bootstrap>'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/initializable.rb:30:in `instance_exec'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/initializable.rb:30:in `run'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/initializable.rb:55:in `block in run_initializers'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/initializable.rb:54:in `each'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/initializable.rb:54:in `run_initializers'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/application.rb:136:in `initialize!'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from D:/row/dev/rickrockstar/config/environment.rb:5:in `<top (required)
>'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/dependencies.rb:251:in `require'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupp
ort-3.2.12/lib/active_support/dependencies.rb:251:in `require'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/application.rb:103:in `require_environment!'
        from D:/row/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3
.2.12/lib/rails/commands.rb:25:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
    ============================================================================

    Your new Refinery CMS application is now installed and mounts at '/'
  ============================================================================
         run  bundle install
```
Do I understand the previous messages correctly that I should make adjustments to some file so that it used decorators version 2.0.0?

**Comment by parndt** [comment]
Did you run this first:

```
gem uninstall decorators --version 1.0.4
```

**Comment by Nickk4** [comment]
Thanks! that solved it!
